Various fixes, create special linecook config

diff --git a/configs/lxblive/config b/configs/lxblive/config
--- a/configs/lxblive/config
+++ b/configs/lxblive/config
@@ -14,13 +14,11 @@ DISTRO=trusty
 
 PROFILE=ubuntu
 
-network_packages="network-manager iproute2 bind9-host iputils-ping ifupdown" # not sure what to do here
-
 # Sets up the default packages to install
-PACKAGES="openssh-server,initramfs-tools,live-boot,lvm2"
+PACKAGES="initramfs-tools,live-boot,network-manager,iproute2,net-tools,ifupdown,iputils-ping,bind9-host"
 
 # Extra packages to be installed after debootstrap
-EXTRA_PACKAGES="vim ${network_packages}"
+EXTRA_PACKAGES="openssh-server lvm2 parted mdadm curl ca-certificates lxc grub-pc vim"
 
 EXCLUDE_PATTERN=()
 
@@ -37,15 +35,38 @@ customize(){
 
 cat > "${CONTAINER_HOME}/${CONTAINER_NAME}/rootfs/etc/rc.local" << EOF
 #!/bin/sh -e
+set -x
 
+wait_network()
+{
+  MAX_RETRIES=6
+  retries=0
+  echo "Waiting for network"
+  while [ -z "\$(ip route | grep 'default' | awk '{print \$3}')" ];do
+    ip="\$(ip route | grep 'default' | awk '{print \$3}')"
+    if [ -n "\${ip}" ];then
+      ping -t 1 -c 1 \${ip} > /dev/null
+      [ \$? -eq 0 ] && break
+    fi
+    retries=\$[\$retries +1]
+    if [ \$retries -gt \$MAX_RETRIES ];then
+      echo "Network failed to come up"
+      exit 1
+    fi
+    sleep 5
+  done
+  echo "Network is up"
+}
+
+wait_network
 # Fetch and run script at onboot_script_url if given
-if [ -n "\$(onboot_script_url= /proc/cmdline)" ];then
+if [ -n "\$(grep onboot_script_url= /proc/cmdline)" ];then
 
   # Read the script URL from /proc/cmdline
-  url_param=$(grep -o 'onboot_script_url=\S*\s' /proc/cmdline)
-  url=$(${url_param#onboot_script_url=})
+  url_param=\$(grep -o 'onboot_script_url=\S*' /proc/cmdline)
+  url=\${url_param#onboot_script_url=}
 
-  curl $url > /onboot_script
+  curl \$url > /onboot_script
   chmod +x /onboot_script
 
   /onboot_script 2>&1 > /var/log/onboot_script.log
@@ -54,5 +75,4 @@ fi
 exit 0
 EOF
   cexec chmod +x "/etc/rc.local"
-
 }
